### ISSUE TITLE
Needs completion

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/cli-interfaces-readme#1]
Have not completed this - was extracted from a different README. The final thing it needs added is a section describing the pseudo-code of a main CLI loop.

Getting input.
Validating it.
Find the correct method or procedure to call.
Getting back to the loop.
Starting it over.
Allowing for exit.

**Comment by AnnJohn** [comment]
@aviflombaum Where in the the CLI applications unit does this go? Is it a new lesson that's not in the spreadsheet or somewhere else?

**Comment by pletcher** [comment]
Thanks for being a part of the Learn community!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

We want to respond as quickly as possible and be as helpful as possible, so please be sure to include steps to reproduce the issue (as best you can remember) and any pertinent details about your environment. (Are you using the Learn IDE? Coding from the ISS?) We'll figure out what's up and get back to you ASAP.
