### ISSUE TITLE
Last hyperlink in this article leads to non-existing webpage

### ISSUE THREAD

**Issue by RemoRemovich** [learn-co-curriculum/cli-interfaces-readme#4]
Last hyperlink in this article (it's located at the end of this article) leads to a non-existing webpage - https://learn.co/lessons/cli-interfaces-readme . I don't know where it should lead, so I leave this issue for developers' judgement.

**Comment by gj** [comment]
Hi @RemoRemovich,

Don't worry about that URL — it's not a bug. 🙂
